### PR TITLE
Buffer Data Type Support added

### PR DESCRIPTION
**Pull request by jannicars**
This commit adds buffer data type support.

### CODE REVIEW

**Comment by jannicars** [comment]
https://github.com/phretaddin/schemapack/pull/12 Here we go

**Comment by jannicars** [comment]
Just found an error when trying to create a single item buffer schema like so:

```javascript
var builtSchema = sp.build("buffer");
var buffer = builtSchema.encode(new Buffer([0x69]));
var item = builtSchema.decode(buffer);
console.log(item);
```

Do you an idea why?

**Comment by phretaddin** [comment]
Just woke up. Yeah, I see why that's happening and see some other issues. Give me a bit to make the changes then I'll merge and commit the fixes.

**Comment by phretaddin** [comment]
Just had a thought while reading your code: maybe we should approach this in a different way.

With this approach, you will only be able to send and receive `Uint8Array`s. What if someone wanted to encode or decode a `Float32Array`, for example?

What if instead we made it so that arrays of single types are implicitly converted to their corresponding indexed collection?

For example, `{ "key": [ "uint8" ] }` would automatically be made a `Uint8Array`, and `{ "key": [ "float32" ] }` would be made a `Float32Array`. The public interface of arrays and collections like `Uint8Array` are virtually identical, and if the user didn't want to use them, they could instead construct the array in the schema like this `{ "key": [ "uint8", "uint8" ] }`

**Comment by jannicars** [comment]
A Buffer in Node is an Uint8Array. I can't think of any use cases right now or I didn't understand your suggestion correctly. For whom would a Float32Array be useful?

**Comment by phretaddin** [comment]
`Float32Array` and `Float64Array` is used a lot for WebGL stuff. `Uint8ClampedArray` is used for Canvas.

I just figured that a `"buffer"` is basically `[ "uint8" ]`, so why not just make `[ "uint8" ]` implicitly convert to a Uint8Array, and at the same time that would give support to any of the other indexed collections should someone need them.

**Comment by jannicars** [comment]
Yep, sounds like a good idea. But what I would like to keep is the buffer as data type. Maybe we can add it as an alias for `[ "uint8" ]`? So in that way I can still easily pass my Buffer via buffer data type and when someone needs a `Float32Array`, this person can easily stick to the "advanced" data type. 

Would that be a good solution?

**Comment by phretaddin** [comment]
Yeah, I'm having second thoughts about my suggestion, just because I doubt many people will be sending pixel data over WebSockets, and they're slower to create than arrays. For now we can add just `buffer`, and if anyone in the future expresses demand for what I mentioned above, we can work on it then.

Ok, so that being the case, let me finish up the fixes to your code then I'll merge+commit.

**Comment by phretaddin** [comment]
Also, this may be unfounded, but do you think this line is okay?

`var buff = buffer.slice(bag.byteOffset, bag.byteOffset + len);`

I'm worried that if someone tried to decode the same buffer in to two objects, and then someone modified one of the the buffers in the objects, wouldn't it affect the other one as well since slice references the same memory instead of copying?

**Comment by jannicars** [comment]
https://nodejs.org/api/buffer.html#buffer_buf_slice_start_end

> Note that modifying the new Buffer slice will modify the memory in the original Buffer because the allocated memory of the two objects overlap.

Hmm, I didn't think about this. Yep, indeed it would be good if the original buffer would stay the same after decoding.

I don't know any other method to read from a buffer except of `copy` but I'm not sure here about the performance... https://nodejs.org/api/buffer.html#buffer_buf_copy_targetbuffer_targetstart_sourcestart_sourceend

Or we keep it like this and add to the documentation that we don't copy the buffer, we slice the buffer from the original buffer and thus it's referenced.

**Comment by phretaddin** [comment]
Ok just committed it all. Let me know if you see any issues with it.

**Pull request merged**
